### ISSUE TITLE
Template Admin: More language string missing

### ISSUE THREAD

**Issue by ptopenweb** [YJSGframework/yjsg#14]
Check the images below

Image 1:
![translate-missing-1](https://cloud.githubusercontent.com/assets/7467959/5959282/dc3156a8-a7c4-11e4-8bf6-6f2932e0ed69.jpg)
--------------------------------
Image 2:
![translate-missing-2](https://cloud.githubusercontent.com/assets/7467959/5959284/dc335e6c-a7c4-11e4-9723-eaec49378312.jpg)
--------------------------------
Image 3:
![translate-missing-3](https://cloud.githubusercontent.com/assets/7467959/5959283/dc320cec-a7c4-11e4-8b78-ab360f63b7d0.jpg)
--------------------------------
Image 4:
![translate-missing-4](https://cloud.githubusercontent.com/assets/7467959/5959285/dc363b82-a7c4-11e4-9996-0812cd62c058.jpg)
--------------------------------
Image 5:
![translate-missing-5](https://cloud.githubusercontent.com/assets/7467959/5959287/dc372830-a7c4-11e4-8bc7-2dc4370aabb7.jpg)
--------------------------------
Image 6:
![translate-missing-6](https://cloud.githubusercontent.com/assets/7467959/5959286/dc37450e-a7c4-11e4-8b7f-364d67217755.jpg)
--------------------------------
Image 7:
![translate-missing-7](https://cloud.githubusercontent.com/assets/7467959/5959288/dc47b1e6-a7c4-11e4-9309-dc2c318a05d2.jpg)
--------------------------------
Image 8:
![translate-missing-8](https://cloud.githubusercontent.com/assets/7467959/5959289/dc48513c-a7c4-11e4-8a7f-4febfd43e79c.jpg)
--------------------------------
Image 9:
![translate-missing-9](https://cloud.githubusercontent.com/assets/7467959/5959359/719972ac-a7c5-11e4-80d9-dfb2fc7f8a1e.jpg)
--------------------------------
Image 10:
![translate-missing-10](https://cloud.githubusercontent.com/assets/7467959/5959293/dc4ffd1a-a7c4-11e4-9993-87073c64fa34.jpg)
--------------------------------
Image 11:
![translate-missing-11](https://cloud.githubusercontent.com/assets/7467959/5959292/dc4fb512-a7c4-11e4-969d-87a1c18edd3c.jpg)
--------------------------------
Image 12:
![translate-missing-12](https://cloud.githubusercontent.com/assets/7467959/5959291/dc4f37f4-a7c4-11e4-9c40-5d072555e505.jpg)
--------------------------------
Image 13:
![translate-missing-13](https://cloud.githubusercontent.com/assets/7467959/5959294/dc5dfec4-a7c4-11e4-8727-5dc73f9bad74.jpg)

**Comment by danyj** [comment]
please go trough #11 , I advised that few of those are framework which we submitted fixes for the ones advised. And I aslo advised that JS ones from jquery plugins are not to be touched. Than you have template ones , and template xml ones. So they do not belong here.
Especially color ones , they will be as they are since template is always changing the name of the styles so framework cannot set defaults for it.  

Go trough templateDetails.xml and you cann add YJSG langs strings but again , they do not belong to the plugin and template fixes should not be submitted in this repo. 

We advised that we will take this in consideration #12

**Comment by ptopenweb** [comment]
oh ok. i didn't read them thanks.
